#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$PARENT_DIR/build"
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

cmake ..
make && make install
